# Kustomize entrypoint — couche app (8 microservices + UI + Ingress).
# Ordre via sync-waves : configmap 0, service-registry 1, services+UI 2, ingress 3.
# NOTE CI : le pipeline GitLab ajoute ici un bloc `images:` (kustomize edit set image)
# pour épingler le tag déployé. Ne pas l'éditer à la main.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- service-registry.yaml
- order-service.yaml
- inventory-service.yaml
- payment-service.yaml
- shipping-service.yaml
- notification-service.yaml
- api-gateway.yaml
- ecommerce-ui.yaml
- ingress.yaml
images:
- name: ghcr.io/youssefabidi69/api-gateway
  newName: ghcr.io/youssefabidi69/api-gateway
  newTag: e7d32ae7
- name: ghcr.io/youssefabidi69/ecommerce-ui
  newName: ghcr.io/youssefabidi69/ecommerce-ui
  newTag: e7d32ae7
- name: ghcr.io/youssefabidi69/inventory-service
  newName: ghcr.io/youssefabidi69/inventory-service
  newTag: e7d32ae7
- name: ghcr.io/youssefabidi69/notification-service
  newName: ghcr.io/youssefabidi69/notification-service
  newTag: e7d32ae7
- name: ghcr.io/youssefabidi69/order-service
  newName: ghcr.io/youssefabidi69/order-service
  newTag: e7d32ae7
- name: ghcr.io/youssefabidi69/payment-service
  newName: ghcr.io/youssefabidi69/payment-service
  newTag: e7d32ae7
- name: ghcr.io/youssefabidi69/service-registry
  newName: ghcr.io/youssefabidi69/service-registry
  newTag: e7d32ae7
- name: ghcr.io/youssefabidi69/shipping-service
  newName: ghcr.io/youssefabidi69/shipping-service
  newTag: e7d32ae7
